version = 1

exclude_patterns = [
    ".debug/*",
    "dist/*",
    "build/*",
    "docs/*",
    "shovel/*"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"