from PyQt5.QtCore import pyqtSlot
from signals import Signals
import toml


class Settings(Signals):

    """All the Settings related stuff for JNote goes Here"""

    def __init__(self, parent=None):
        super().__init__(parent)

    @pyqtSlot(str, str, str)
    def setSettingsStr(self, category, key, value):
        """Set string settings"""
        try:
            with open("settings.toml", "r") as settings:
                toml_object = toml.load(settings)
            toml_object[category][key] = value
            with open("settings.toml", "w") as settings:
                toml.dump(toml_object, settings)
        except FileNotFoundError:
            self.settingsFileNotFound.emit()
        except toml.TomlDecodeError:
            self.settingsError.emit()
        except BaseException:
            self.fatalError.emit()

    @pyqtSlot(str, str, int)
    def setSettingsInt(self, category, key, value):
        """Set integer settings"""
        try:
            with open("settings.toml", "r") as settings:
                toml_object = toml.load(settings)
            toml_object[category][key] = value
            with open("settings.toml", "w") as settings:
                toml.dump(toml_object, settings)
        except FileNotFoundError:
            self.settingsFileNotFound.emit()
        except toml.TomlDecodeError:
            self.settingsError.emit()
        except BaseException:
            self.fatalError.emit()

    @pyqtSlot(str, str, bool)
    def setSettingsBool(self, category, key, value):
        """Set Boolean Settings"""
        try:
            with open("settings.toml", "r") as settings:
                toml_object = toml.load(settings)
            toml_object[category][key] = value
            with open("settings.toml", "w") as settings:
                toml.dump(toml_object, settings)
        except FileNotFoundError:
            self.settingsFileNotFound.emit()
        except toml.TomlDecodeError:
            self.settingsError.emit()
        except BaseException:
            self.fatalError.emit()

    @pyqtSlot(str, result='QVariant')
    def getSettings(self, category):
        """Get any setting"""
        toml_object = {}
        try:
            with open("settings.toml", "r") as settings:
                toml_object = toml.load(settings)
        except FileNotFoundError:
            self.settingsFileNotFound.emit()
        except toml.TomlDecodeError:
            self.settingsError.emit()
        except BaseException:
            self.fatalError.emit()
        return toml_object[category]

    @pyqtSlot()
    def addComments(self):
        comments = """\
# DO NOT DELETE OR MODIFY THIS FILE! DOING SO WILL DAMAGE JNOTE!!
# This File is Automatically Generated and is not for adding
# user's preferences.
# These are some small settings used to enhance your experience with
# JNote but not to, Edit or DELETE.
# Doing so will do nothing but only ruin your experience!!!

"""
        with open("settings.toml", "r") as settings:
            settingsString = settings.read()
        with open("settings.toml", "w") as settings:
            settings.write(comments + settingsString)
